name: akcess
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_launcher_icons: ^0.14.0
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  http: ^1.2.2
  intl: any

flutter_launcher_icons:
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptive_icon_background: "#FFFFFF"
  image_path: "assets/logo/logo-primary.png"
  adaptive_icon_foreground: "assets/logo/logo-primary.png"

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter/Inter-Black.ttf
