name: akcess
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  animated_text_kit: ^4.2.2
  country_currency_pickers: ^3.0.0
  cupertino_icons: ^1.0.8
  diacritic: ^0.1.6
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_launcher_icons: ^0.14.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  get_it: ^8.0.0
  http: ^1.2.2
  intl: any
  lucide_icons: ^0.257.0
  popover: ^0.3.1

flutter_launcher_icons:
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptive_icon_background: "#FFFFFF"
  image_path: "assets/logo/logo-primary.png"
  adaptive_icon_foreground: "assets/logo/logo-primary.png"

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_28pt-Black.ttf
        - asset: assets/fonts/Inter_28pt-Bold.ttf
        - asset: assets/fonts/Inter_28pt-ExtraBold.ttf
        - asset: assets/fonts/Inter_28pt-ExtraLight.ttf
        - asset: assets/fonts/Inter_28pt-Light.ttf
        - asset: assets/fonts/Inter_28pt-Medium.ttf
        - asset: assets/fonts/Inter_28pt-Regular.ttf
        - asset: assets/fonts/Inter_28pt-SemiBold.ttf
        - asset: assets/fonts/Inter_28pt-Thin.ttf
